import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#0f5238",
        "on-primary": "#ffffff",
        "primary-container": "#2d6a4f",
        "on-primary-container": "#a8e7c5",
        "primary-fixed": "#b1f0ce",
        "primary-fixed-dim": "#95d4b3",
        "on-primary-fixed": "#002114",
        "on-primary-fixed-variant": "#0e5138",
        "inverse-primary": "#95d4b3",
        secondary: "#116c4a",
        "on-secondary": "#ffffff",
        "secondary-container": "#a1f4c8",
        "on-secondary-container": "#1b724f",
        "secondary-fixed": "#a1f4c8",
        "secondary-fixed-dim": "#86d7ad",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",
        tertiary: "#8e1700",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#b72607",
        "on-tertiary-container": "#ffcfc5",
        "tertiary-fixed": "#ffdad3",
        "tertiary-fixed-dim": "#ffb4a4",
        "on-tertiary-fixed": "#3e0500",
        "on-tertiary-fixed-variant": "#8d1600",
        surface: "#e8fff0",
        "surface-dim": "#b8e4cc",
        "surface-bright": "#e8fff0",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#d1fee5",
        "surface-container": "#ccf8df",
        "surface-container-high": "#c6f2da",
        "surface-container-highest": "#c1ecd4",
        "on-surface": "#002114",
        "on-surface-variant": "#404943",
        "surface-variant": "#c1ecd4",
        "surface-tint": "#2c694e",
        "inverse-surface": "#0e3727",
        "inverse-on-surface": "#cffbe2",
        background: "#e8fff0",
        "on-background": "#002114",
        outline: "#707973",
        "outline-variant": "#bfc9c1",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "electric-blue": "#3B82F6",
        "shopee-orange": "#EE4D2D",
        "light-sage": "#E8F5E2",
        "deep-forest": "#1B4332",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "16px",
        md: "24px",
        lg: "40px",
        xl: "64px",
        gutter: "20px",
        "margin-mobile": "16px",
        "margin-desktop": "80px",
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["DM Sans", "sans-serif"],
        "accent-text": ["DM Sans", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "accent-text": ["14px", { lineHeight: "20px", fontWeight: "500" }],
      },
      boxShadow: {
        card: "0 2px 8px rgba(0,0,0,0.08)",
        premium: "0 4px 16px rgba(0,0,0,0.12)",
      },
      keyframes: {
        scan: {
          "0%": { top: "0%", opacity: "0" },
          "10%": { opacity: "1" },
          "90%": { opacity: "1" },
          "100%": { top: "100%", opacity: "0" },
        },
        pulse_blue: {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(59,130,246,0.4)" },
          "50%": { boxShadow: "0 0 0 8px rgba(59,130,246,0)" },
        },
        fadeInUp: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        scan: "scan 2s infinite linear",
        pulse_blue: "pulse_blue 2s infinite",
        fadeInUp: "fadeInUp 0.5s ease-out forwards",
      },
    },
  },
  plugins: [],
};

export default config;
